language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "nightly"
# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script:
  - python manage.py migrate;                  # Apply South's database migrations
  - python manage.py jenkins --enable-coverage;
